### ISSUE TITLE
Doubts about loops?

### ISSUE THREAD

**Issue by 2505817596** [Cysharp/LogicLooper#11]
Shouldn't this loop 60 times a second, why is it 30 times?
![image](https://user-images.githubusercontent.com/37748815/129475934-b18bcbf9-10d5-4901-981e-5414b270b326.png)

**Comment by binhnguyen86** [comment]
any update for it @mayuki

**Comment by mayuki** [comment]
Approaches to changing the accuracy of Windows timers to avoid this problem have been available for some time.
https://stackoverflow.com/questions/3744032/why-are-net-timers-limited-to-15-ms-resolution

`timeBeginPeriod` Win32 API can be used to change the timer accuracy on Windows.
https://docs.microsoft.com/ja-jp/windows/win32/api/timeapi/nf-timeapi-timebeginperiod

On Windows 10 version 2004 or later, the timer precision can be changed on a process-by-process basis, so there should be no problem with this method.
